<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>booleanrule</name>
  <uuid>e06b972e-1a88-4bf9-816c-f174480451bd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Input is "Harshul"
then
    set decision to true ;
else 
    set decision to false; 

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
